import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from '@/providers/ThemeProvider';
import { ThemeSwitcher } from '@/components/Theme/ThemeSwitcher';
import { ButtonColorMenu } from '@/components/Theme/ButtonColorMenu';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <ThemeProvider>
          <html lang="en">
          <body className="min-h-screen bg-gray-100 dark:bg-gray-900">
          <div className="p-4 flex items-center justify-between">
              <ThemeSwitcher />
              <ButtonColorMenu />
          </div>
          <main>{children}</main>
          </body>
          </html>
      </ThemeProvider>
  );
}
